CREATE TABLE IF NOT EXISTS `{{prefix}}files` (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uid VARCHAR(64) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    relative_path VARCHAR(512) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    extension VARCHAR(32) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    sha256 CHAR(64) NOT NULL,
    metadata JSON NULL,
    width INT UNSIGNED NULL,
    height INT UNSIGNED NULL,
    color_scheme VARCHAR(32) NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'general',
    alt_text VARCHAR(500) NULL,
    uploaded_by VARCHAR(32) NOT NULL DEFAULT 'api',
    source_ip VARCHAR(45) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_files_uid (uid),
    KEY idx_files_created_at (created_at),
    KEY idx_files_extension (extension),
    KEY idx_files_sha256 (sha256),
    KEY idx_files_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
